const table = [
  {
    symbol: "H",
    name: "Hydrogen",
    atomicWeight: "1.00794",
    atomicNumber: 1,
    row: 1,
    column: 1,
  },
  {
    symbol: "He",
    name: "Helium",
    atomicWeight: "4.002602",
    atomicNumber: 2,
    row: 1,
    column: 18,
  },
  {
    symbol: "Li",
    name: "Lithium",
    atomicWeight: "6.941",
    atomicNumber: 3,
    row: 2,
    column: 1,
  },
  {
    symbol: "Be",
    name: "Beryllium",
    atomicWeight: "9.012182",
    row: 2,
    column: 2,
    atomicNumber: 4,
  },
  {
    symbol: "B",
    name: "Boron",
    atomicWeight: "10.811",
    row: 2,
    column: 13,
    atomicNumber: 5,
  },
  {
    symbol: "C",
    name: "Carbon",
    atomicWeight: "12.0107",
    row: 2,
    column: 14,
    atomicNumber: 6,
  },
  {
    symbol: "N",
    name: "Nitrogen",
    atomicWeight: "14.0067",
    row: 2,
    column: 15,
    atomicNumber: 7,
  },
  {
    symbol: "O",
    name: "Oxygen",
    atomicWeight: "15.9994",
    row: 2,
    column: 16,
    atomicNumber: 8,
  },
  {
    symbol: "F",
    name: "Fluorine",
    atomicWeight: "18.9984032",
    row: 2,
    column: 17,
    atomicNumber: 9,
  },
  {
    symbol: "Ne",
    name: "Neon",
    atomicWeight: "20.1797",
    row: 2,
    column: 18,
    atomicNumber: 10,
  },
  {
    symbol: "Na",
    name: "Sodium",
    atomicWeight: "22.989769",
    row: 3,
    column: 1,
    atomicNumber: 11,
  },
  {
    symbol: "Mg",
    name: "Magnesium",
    atomicWeight: "24.305",
    row: 3,
    column: 2,
    atomicNumber: 12,
  },
  {
    symbol: "Al",
    name: "Aluminium",
    atomicWeight: "26.9815386",
    row: 3,
    column: 13,
    atomicNumber: 13,
  },
  {
    symbol: "Si",
    name: "Silicon",
    atomicWeight: "28.0855",
    row: 3,
    column: 14,
    atomicNumber: 14,
  },
  {
    symbol: "P",
    name: "Phosphorus",
    atomicWeight: "30.973762",
    row: 3,
    column: 15,
    atomicNumber: 15,
  },
  {
    symbol: "S",
    name: "Sulfur",
    atomicWeight: "32.065",
    row: 3,
    column: 16,
    atomicNumber: 16,
  },
  {
    symbol: "Cl",
    name: "Chlorine",
    atomicWeight: "35.453",
    row: 3,
    column: 17,
    atomicNumber: 17,
  },
  {
    symbol: "Ar",
    name: "Argon",
    atomicWeight: "39.948",
    row: 3,
    column: 18,
    atomicNumber: 18,
  },
  {
    symbol: "K",
    name: "Potassium",
    atomicWeight: "39.948",
    row: 4,
    column: 1,
    atomicNumber: 19,
  },
  {
    symbol: "Ca",
    name: "Calcium",
    atomicWeight: "40.078",
    row: 4,
    column: 2,
    atomicNumber: 20,
  },
  {
    symbol: "Sc",
    name: "Scandium",
    atomicWeight: "44.955912",
    row: 4,
    column: 3,
    atomicNumber: 21,
  },
  {
    symbol: "Ti",
    name: "Titanium",
    atomicWeight: "47.867",
    row: 4,
    column: 4,
    atomicNumber: 22,
  },
  {
    symbol: "V",
    name: "Vanadium",
    atomicWeight: "50.9415",
    row: 4,
    column: 5,
    atomicNumber: 23,
  },
  {
    symbol: "Cr",
    name: "Chromium",
    atomicWeight: "51.9961",
    row: 4,
    column: 6,
    atomicNumber: 24,
  },
  {
    symbol: "Mn",
    name: "Manganese",
    atomicWeight: "54.938045",
    row: 4,
    column: 7,
    atomicNumber: 25,
  },
  {
    symbol: "Fe",
    name: "Iron",
    atomicWeight: "55.845",
    row: 4,
    column: 8,
    atomicNumber: 26,
  },
  {
    symbol: "Co",
    name: "Cobalt",
    atomicWeight: "58.933195",
    row: 4,
    column: 9,
    atomicNumber: 27,
  },
  {
    symbol: "Ni",
    name: "Nickel",
    atomicWeight: "58.6934",
    row: 4,
    column: 10,
    atomicNumber: 28,
  },
  {
    symbol: "Cu",
    name: "Copper",
    atomicWeight: "63.546",
    row: 4,
    column: 11,
    atomicNumber: 29,
  },
  {
    symbol: "Zn",
    name: "Zinc",
    atomicWeight: "65.38",
    row: 4,
    column: 12,
    atomicNumber: 30,
  },
  {
    symbol: "Ga",
    name: "Gallium",
    atomicWeight: "69.723",
    row: 4,
    column: 13,
    atomicNumber: 31,
  },
  {
    symbol: "Ge",
    name: "Germanium",
    atomicWeight: "72.63",
    row: 4,
    column: 14,
    atomicNumber: 32,
  },
  {
    symbol: "As",
    name: "Arsenic",
    atomicWeight: "74.9216",
    row: 4,
    column: 15,
    atomicNumber: 33,
  },
  {
    symbol: "Se",
    name: "Selenium",
    atomicWeight: "78.96",
    row: 4,
    column: 16,
    atomicNumber: 34,
  },
  {
    symbol: "Br",
    name: "Bromine",
    atomicWeight: "79.904",
    row: 4,
    column: 17,
    atomicNumber: 35,
  },
  {
    symbol: "Kr",
    name: "Krypton",
    atomicWeight: "83.798",
    row: 4,
    column: 18,
    atomicNumber: 36,
  },
  {
    symbol: "Rb",
    name: "Rubidium",
    atomicWeight: "85.4678",
    row: 5,
    column: 1,
    atomicNumber: 37,
  },
  {
    symbol: "Sr",
    name: "Strontium",
    atomicWeight: "87.62",
    row: 5,
    column: 2,
    atomicNumber: 38,
  },
  {
    symbol: "Y",
    name: "Yttrium",
    atomicWeight: "88.90585",
    row: 5,
    column: 3,
    atomicNumber: 39,
  },
  {
    symbol: "Zr",
    name: "Zirconium",
    atomicWeight: "91.224",
    row: 5,
    column: 4,
    atomicNumber: 40,
  },
  {
    symbol: "Nb",
    name: "Niobium",
    atomicWeight: "92.90628",
    row: 5,
    column: 5,
    atomicNumber: 41,
  },
  {
    symbol: "Mo",
    name: "Molybdenum",
    atomicWeight: "95.96",
    row: 5,
    column: 6,
    atomicNumber: 42,
  },
  {
    symbol: "Tc",
    name: "Technetium",
    atomicWeight: "98",
    row: 5,
    column: 7,
    atomicNumber: 43,
  },
  {
    symbol: "Ru",
    name: "Ruthenium",
    atomicWeight: "101.07",
    row: 5,
    column: 8,
    atomicNumber: 44,
  },
  {
    symbol: "Rh",
    name: "Rhodium",
    atomicWeight: "102.9055",
    row: 5,
    column: 9,
    atomicNumber: 45,
  },
  {
    symbol: "Pd",
    name: "Palladium",
    atomicWeight: "106.42",
    row: 5,
    column: 10,
    atomicNumber: 46,
  },
  {
    symbol: "Ag",
    name: "Silver",
    atomicWeight: "107.8682",
    row: 5,
    column: 11,
    atomicNumber: 47,
  },
  {
    symbol: "Cd",
    name: "Cadmium",
    atomicWeight: "112.411",
    row: 5,
    column: 12,
    atomicNumber: 48,
  },
  {
    symbol: "In",
    name: "Indium",
    atomicWeight: "114.818",
    row: 5,
    column: 13,
    atomicNumber: 49,
  },
  {
    symbol: "Sn",
    name: "Tin",
    atomicWeight: "118.71",
    row: 5,
    column: 14,
    atomicNumber: 50,
  },
  {
    symbol: "Sb",
    name: "Antimony",
    atomicWeight: "121.76",
    row: 5,
    column: 15,
    atomicNumber: 51,
  },
  {
    symbol: "Te",
    name: "Tellurium",
    atomicWeight: "127.6",
    row: 5,
    column: 16,
    atomicNumber: 52,
  },
  {
    symbol: "I",
    name: "Iodine",
    atomicWeight: "126.90447",
    row: 5,
    column: 17,
    atomicNumber: 53,
  },
  {
    symbol: "Xe",
    name: "Xenon",
    atomicWeight: "131.293",
    row: 5,
    column: 18,
    atomicNumber: 54,
  },
  {
    symbol: "Cs",
    name: "Caesium",
    atomicWeight: "132.9054",
    row: 6,
    column: 1,
    atomicNumber: 55,
  },
  {
    symbol: "Ba",
    name: "Barium",
    atomicWeight: "137.327",
    row: 6,
    column: 2,
    atomicNumber: 56,
  },
  {
    symbol: "Hf",
    name: "Hafnium",
    atomicWeight: "178.49",
    row: 6,
    column: 4,
    atomicNumber: 72,
  },
  {
    symbol: "Ta",
    name: "Tantalum",
    atomicWeight: "180.94788",
    row: 6,
    column: 5,
    atomicNumber: 73,
  },
  {
    symbol: "W",
    name: "Tungsten",
    atomicWeight: "183.84",
    row: 6,
    column: 6,
    atomicNumber: 74,
  },
  {
    symbol: "Re",
    name: "Rhenium",
    atomicWeight: "186.207",
    row: 6,
    column: 7,
    atomicNumber: 75,
  },
  {
    symbol: "Os",
    name: "Osmium",
    atomicWeight: "190.23",
    row: 6,
    column: 8,
    atomicNumber: 76,
  },
  {
    symbol: "Ir",
    name: "Iridium",
    atomicWeight: "192.217",
    row: 6,
    column: 9,
    atomicNumber: 77,
  },
  {
    symbol: "Pt",
    name: "Platinum",
    atomicWeight: "195.084",
    row: 6,
    column: 10,
    atomicNumber: 78,
  },
  {
    symbol: "Au",
    name: "Gold",
    atomicWeight: "196.966569",
    row: 6,
    column: 11,
    atomicNumber: 79,
  },
  {
    symbol: "Hg",
    name: "Mercury",
    atomicWeight: "200.59",
    row: 6,
    column: 12,
    atomicNumber: 80,
  },
  {
    symbol: "Tl",
    name: "Thallium",
    atomicWeight: "204.3833",
    row: 6,
    column: 13,
    atomicNumber: 81,
  },
  {
    symbol: "Pb",
    name: "Lead",
    atomicWeight: "207.2",
    row: 6,
    column: 14,
    atomicNumber: 82,
  },
  {
    symbol: "Bi",
    name: "Bismuth",
    atomicWeight: "208.9804",
    row: 6,
    column: 15,
    atomicNumber: 83,
  },
  {
    symbol: "Po",
    name: "Polonium",
    atomicWeight: "209",
    row: 6,
    column: 16,
    atomicNumber: 84,
  },
  {
    symbol: "At",
    name: "Astatine",
    atomicWeight: "210",
    row: 6,
    column: 17,
    atomicNumber: 85,
  },
  {
    symbol: "Rn",
    name: "Radon",
    atomicWeight: "222",
    row: 6,
    column: 18,
    atomicNumber: 86,
  },
  {
    symbol: "Fr",
    name: "Francium",
    atomicWeight: "223",
    row: 7,
    column: 1,
    atomicNumber: 87,
  },
  {
    symbol: "Ra",
    name: "Radium",
    atomicWeight: "226",
    row: 7,
    column: 2,
    atomicNumber: 88,
  },
  {
    symbol: "Rf",
    name: "Rutherfordium",
    atomicWeight: "267",
    row: 4,
    column: 7,
    atomicNumber: 104,
  },
  {
    symbol: "Db",
    name: "Dubnium",
    atomicWeight: "268",
    row: 7,
    column: 5,
    atomicNumber: 105,
  },
  {
    symbol: "La",
    name: "Lanthanum",
    atomicWeight: "138.90547",
    row: 6,
    column: 3,
    atomicNumber: 57,
  },
  {
    symbol: "Ce",
    name: "Cerium",
    atomicWeight: "140.116",
    row: 9,
    column: 5,
    atomicNumber: 58,
  },
  {
    symbol: "Pr",
    name: "Praseodymium",
    atomicWeight: "140.90765",
    row: 9,
    column: 6,
    atomicNumber: 59,
  },
  {
    symbol: "Nd",
    name: "Neodymium",
    atomicWeight: "144.242",
    row: 9,
    column: 7,
    atomicNumber: 60,
  },
  {
    symbol: "Pm",
    name: "Promethium",
    atomicWeight: "145",
    row: 9,
    column: 8,
    atomicNumber: 61,
  },
  {
    symbol: "Sm",
    name: "Samarium",
    atomicWeight: "150.36",
    row: 9,
    column: 9,
    atomicNumber: 62,
  },
  {
    symbol: "Eu",
    name: "Europium",
    atomicWeight: "151.964",
    row: 9,
    column: 10,
    atomicNumber: 63,
  },
  {
    symbol: "Gd",
    name: "Gadolinium",
    atomicWeight: "157.25",
    row: 9,
    column: 11,
    atomicNumber: 64,
  },
  {
    symbol: "Tb",
    name: "Terbium",
    atomicWeight: "158.92535",
    row: 9,
    column: 12,
    atomicNumber: 65,
  },
  {
    symbol: "Dy",
    name: "Dysprosium",
    atomicWeight: "162.5",
    row: 9,
    column: 13,
    atomicNumber: 66,
  },
  {
    symbol: "Ho",
    name: "Holmium",
    atomicWeight: "164.93032",
    row: 9,
    column: 14,
    atomicNumber: 67,
  },
  {
    symbol: "Er",
    name: "Erbium",
    atomicWeight: "167.259",
    row: 9,
    column: 15,
    atomicNumber: 68,
  },
  {
    symbol: "Tm",
    name: "Thulium",
    atomicWeight: "168.93421",
    row: 9,
    column: 16,
    atomicNumber: 69,
  },
  {
    symbol: "Yb",
    name: "Ytterbium",
    atomicWeight: "173.04",
    row: 9,
    column: 17,
    atomicNumber: 70,
  },
  {
    symbol: "Lu",
    name: "Lutetium",
    atomicWeight: "174.9668",
    row: 9,
    column: 18,
    atomicNumber: 71,
  },
  {
    symbol: "Ac",
    name: "Actinium",
    atomicWeight: "227",
    row: 7,
    column: 3,
    atomicNumber: 89,
  },
  {
    symbol: "Th",
    name: "Thorium",
    atomicWeight: "232.03806",
    row: 10,
    column: 5,
    atomicNumber: 90,
  },
  {
    symbol: "Pa",
    name: "Protactinium",
    atomicWeight: "231.0588",
    row: 10,
    column: 6,
    atomicNumber: 91,
  },
  {
    symbol: "U",
    name: "Uranium",
    atomicWeight: "238.02891",
    row: 10,
    column: 7,
    atomicNumber: 92,
  },
  {
    symbol: "Np",
    name: "Neptunium",
    atomicWeight: "237",
    row: 10,
    column: 8,
    atomicNumber: 93,
  },
  {
    symbol: "Pu",
    name: "Plutonium",
    atomicWeight: "244",
    row: 10,
    column: 9,
    atomicNumber: 94,
  },
  {
    symbol: "Am",
    name: "Americium",
    atomicWeight: "243",
    row: 10,
    column: 10,
    atomicNumber: 95,
  },
  {
    symbol: "Cm",
    name: "Curium",
    atomicWeight: "247",
    row: 10,
    column: 11,
    atomicNumber: 96,
  },
  {
    symbol: "Bk",
    name: "Berkelium",
    atomicWeight: "247",
    row: 10,
    column: 12,
    atomicNumber: 97,
  },
  {
    symbol: "Cf",
    name: "Californium",
    atomicWeight: "251",
    row: 10,
    column: 13,
    atomicNumber: 98,
  },
  {
    symbol: "Es",
    name: "Einstenium",
    atomicWeight: "252",
    row: 10,
    column: 14,
    atomicNumber: 99,
  },
  {
    symbol: "Fm",
    name: "Fermium",
    atomicWeight: "257",
    row: 10,
    column: 15,
    atomicNumber: 100,
  },
  {
    symbol: "Md",
    name: "Mendelevium",
    atomicWeight: "258",
    row: 10,
    column: 16,
    atomicNumber: 101,
  },
  {
    symbol: "No",
    name: "Nobelium",
    atomicWeight: "259",
    row: 10,
    column: 17,
    atomicNumber: 102,
  },
  {
    symbol: "Lr",
    name: "Lawrencium",
    atomicWeight: "262",
    row: 10,
    column: 18,
    atomicNumber: 103,
  },

  {
    symbol: "Rf",
    name: "Rutherfordium",
    atomicWeight: "267",
    row: 7,
    column: 4,
    atomicNumber: 104,
  },
  {
    symbol: "Db",
    name: "Dubnium",
    atomicWeight: "268",
    row: 5,
    column: 7,
    atomicNumber: 105,
  },
  {
    symbol: "Sg",
    name: "Seaborgium",
    atomicWeight: "271",
    row: 7,
    column: 6,
    atomicNumber: 106,
  },
  {
    symbol: "Bh",
    name: "Bohrium",
    atomicWeight: "272",
    row: 7,
    column: 7,
    atomicNumber: 107,
  },
  {
    symbol: "Hs",
    name: "Hassium",
    atomicWeight: "270",
    row: 7,
    column: 8,
    atomicNumber: 108,
  },
  {
    symbol: "Mt",
    name: "Meitnerium",
    atomicWeight: "276",
    row: 7,
    column: 9,
    atomicNumber: 109,
  },
  {
    symbol: "Ds",
    name: "Darmstadium",
    atomicWeight: "281",
    row: 7,
    column: 10,
    atomicNumber: 110,
  },
  {
    symbol: "Rg",
    name: "Roentgenium",
    atomicWeight: "280",
    row: 7,
    column: 11,
    atomicNumber: 111,
  },
  {
    symbol: "Cn",
    name: "Copernicium",
    atomicWeight: "285",
    row: 7,
    column: 12,
    atomicNumber: 112,
  },
  {
    symbol: "Nh",
    name: "Nihonium",
    atomicWeight: "286",
    row: 7,
    column: 13,
    atomicNumber: 113,
  },
  {
    symbol: "Fl",
    name: "Flerovium",
    atomicWeight: "289",
    row: 7,
    column: 14,
    atomicNumber: 114,
  },
  {
    symbol: "Mc",
    name: "Moscovium",
    atomicWeight: "290",
    row: 7,
    column: 15,
    atomicNumber: 115,
  },
  {
    symbol: "Lv",
    name: "Livermorium",
    atomicWeight: "293",
    row: 7,
    column: 16,
    atomicNumber: 116,
  },
  {
    symbol: "Ts",
    name: "Tennessine",
    atomicWeight: "294",
    row: 7,
    column: 17,
    atomicNumber: 117,
  },
  {
    symbol: "Og",
    name: "Oganesson",
    atomicWeight: "294",
    row: 7,
    column: 18,
    atomicNumber: 118,
  },
];

export default table;
